"""Host 公共入口。

P8-S2 起公开接口仅暴露 contracts 与 :class:`LocalRunHarness`/
:func:`build_durable_harness`（后者由 ``dayu.host._durable_harness``
直接导出）；上层应通过 ``build_durable_harness().harness`` 装配 production /
durable harness，再使用其实例方法（``start_run`` / ``stream_run_events`` /
``get_run_result``）。``LocalRunHarness`` 自身仍是 Host 内部 kernel，但作为
test-only 装配入口被显式暴露。
"""

from __future__ import annotations

from dayu.host.contracts import (
    ContextCompactFailureReason,
    HostContextAttemptRetryData,
    HostContextCompactCompletedData,
    HostContextCompactEventData,
    HostContextCompactFailedData,
    HostContextCompactRequestedData,
    HostContextOverflowObservedData,
    HostRunFailedData,
    RunCancelledResult,
    RunEvent,
    RunEventCursor,
    RunEventData,
    RunEventKind,
    RunEventSource,
    RunEventType,
    RunFailedResult,
    RunHandle,
    RunInput,
    RunOptions,
    RunResult,
    RunState,
    RunStream,
    RunSucceededResult,
    RunSuspendedResult,
    StartRunRequest,
    ToolCursorDeniedData,
    ToolCursorExpiredData,
    ToolCursorIssuedData,
    ToolFetchMoreCompletedData,
    ToolFetchMoreFailedData,
    ToolFetchMoreFailedResult,
    ToolFetchMoreHandle,
    ToolFetchMoreHandleFailedResult,
    ToolFetchMoreHandleRequest,
    ToolFetchMoreHandleResult,
    ToolFetchMoreHandleSucceededResult,
    ToolFetchMoreRequest,
    ToolFetchMoreRequestedData,
    ToolFetchMoreResult,
    ToolFetchMoreSucceededResult,
    ToolResultTruncatedData,
    ToolRuntimeCursor,
    ToolRuntimeEventData,
    ToolValueSizeSummary,
    UserInputAcceptedData,
    UserInputScope,
)

__all__ = [
    "ContextCompactFailureReason",
    "HostContextAttemptRetryData",
    "HostContextCompactCompletedData",
    "HostContextCompactEventData",
    "HostContextCompactFailedData",
    "HostContextCompactRequestedData",
    "HostContextOverflowObservedData",
    "HostRunFailedData",
    "RunCancelledResult",
    "RunEventData",
    "RunEvent",
    "RunEventCursor",
    "RunEventKind",
    "RunEventSource",
    "RunEventType",
    "RunFailedResult",
    "RunHandle",
    "RunInput",
    "RunOptions",
    "RunResult",
    "RunState",
    "RunStream",
    "RunSucceededResult",
    "RunSuspendedResult",
    "StartRunRequest",
    "ToolCursorDeniedData",
    "ToolCursorExpiredData",
    "ToolCursorIssuedData",
    "ToolFetchMoreCompletedData",
    "ToolFetchMoreFailedData",
    "ToolFetchMoreFailedResult",
    "ToolFetchMoreHandle",
    "ToolFetchMoreHandleFailedResult",
    "ToolFetchMoreHandleRequest",
    "ToolFetchMoreHandleResult",
    "ToolFetchMoreHandleSucceededResult",
    "ToolFetchMoreRequest",
    "ToolFetchMoreRequestedData",
    "ToolFetchMoreResult",
    "ToolFetchMoreSucceededResult",
    "ToolResultTruncatedData",
    "ToolRuntimeCursor",
    "ToolRuntimeEventData",
    "ToolValueSizeSummary",
    "UserInputAcceptedData",
    "UserInputScope",
]
