"""Host 公共入口。

P1.5 暴露最小 Run 级入口与事件事实读取接口。Host 内部的 ``EngineWorker``、
``LocalProxy``、``WorkerProxy`` 与 ``ToolExecutor`` 代持不属于 public surface。
"""

from __future__ import annotations

from dayu.host._run_harness import (
    fetch_more_tool_result,
    get_run_result,
    get_tool_fetch_more_handle,
    start_run,
    stream_run_events,
)
from dayu.host.contracts import (
    HostRunFailedData,
    RunCancelledResult,
    RunEvent,
    RunEventCursor,
    RunEventData,
    RunEventKind,
    RunEventSource,
    RunEventType,
    RunFailedResult,
    RunHandle,
    RunInput,
    RunOptions,
    RunResult,
    RunState,
    RunStream,
    RunSucceededResult,
    RunSuspendedResult,
    StartRunRequest,
    ToolCursorDeniedData,
    ToolCursorExpiredData,
    ToolCursorIssuedData,
    ToolFetchMoreCompletedData,
    ToolFetchMoreFailedData,
    ToolFetchMoreFailedResult,
    ToolFetchMoreHandle,
    ToolFetchMoreHandleFailedResult,
    ToolFetchMoreHandleRequest,
    ToolFetchMoreHandleResult,
    ToolFetchMoreHandleSucceededResult,
    ToolFetchMoreRequest,
    ToolFetchMoreRequestedData,
    ToolFetchMoreResult,
    ToolFetchMoreSucceededResult,
    ToolResultTruncatedData,
    ToolRuntimeCursor,
    ToolRuntimeEventData,
    ToolValueSizeSummary,
)

__all__ = [
    "HostRunFailedData",
    "RunCancelledResult",
    "RunEventData",
    "RunEvent",
    "RunEventCursor",
    "RunEventKind",
    "RunEventSource",
    "RunEventType",
    "RunFailedResult",
    "RunHandle",
    "RunInput",
    "RunOptions",
    "RunResult",
    "RunState",
    "RunStream",
    "RunSucceededResult",
    "RunSuspendedResult",
    "StartRunRequest",
    "ToolCursorDeniedData",
    "ToolCursorExpiredData",
    "ToolCursorIssuedData",
    "ToolFetchMoreCompletedData",
    "ToolFetchMoreFailedData",
    "ToolFetchMoreFailedResult",
    "ToolFetchMoreHandle",
    "ToolFetchMoreHandleFailedResult",
    "ToolFetchMoreHandleRequest",
    "ToolFetchMoreHandleResult",
    "ToolFetchMoreHandleSucceededResult",
    "ToolFetchMoreRequest",
    "ToolFetchMoreRequestedData",
    "ToolFetchMoreResult",
    "ToolFetchMoreSucceededResult",
    "ToolResultTruncatedData",
    "ToolRuntimeCursor",
    "ToolRuntimeEventData",
    "ToolValueSizeSummary",
    "fetch_more_tool_result",
    "get_run_result",
    "get_tool_fetch_more_handle",
    "start_run",
    "stream_run_events",
]
